CREATE TABLE Restaurant(
	ID INTEGER PRIMARY KEY,
	Name varchar(25),
	City INTEGER REFERENCES City(ID) ON DELETE SET NULL,
	Counrtry INTEGER REFERENCES Country(ID) ON DELETE SET NULL,
	Menu INTEGER REFERENCES Menu(ID) ON DELETE SET NULL
);

CREATE TABLE Personal(
    ID INTEGER PRIMARY KEY,
    Name VARCHAR(30),
    Position VARCHAR(30),
    Restaurant INTEGER REFERENCES Restaurant(id) ON DELETE SET NULL
);

CREATE TABLE Country(
    ID INTEGER PRIMARY KEY,
    Name VARCHAR(30)
);

CREATE TABLE City(
    ID INTEGER PRIMARY KEY,
    Name VARCHAR(40),
    Counrty INTEGER REFERENCES Country(ID) ON DELETE SET NULL
);

CREATE TABLE Menu(
    ID INTEGER PRIMARY KEY,
    Name VARCHAR(20),
    Season VARCHAR(10)
);

CREATE TABLE Dish(
    ID INTEGER PRIMARY KEY,
    Name VARCHAR(20),
    Description VARCHAR(300),
    Menu int REFERENCES Menu(ID) ON DELETE SET NULL
);