version: '3.7'

services:
  web:
    build: .
    command: python wsgi.py run
    ports:
      - 8000:5000
    links:
      - db
    depends_on:
      - db
    restart: on-failure

  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=cursor
      - POSTGRES_PASSWORD=very_secret_password
      - POSTGRES_DB=cursor_db_alchemy
    ports:
      - 5433:5432
